/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Home
 */
public class S2M12021_Proyecto02 extends javax.swing.JFrame {

    /**
     * Creates new form S2M12021_Proyecto02
     */
    public S2M12021_Proyecto02() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido #001"));

        jButton3.setText("Estado");
        jPanel3.add(jButton3);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Turno:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 30, 32, 14);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(30, 50, 80, 30);

        jLabel2.setText("Hora estimada de entrega:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 30, 170, 14);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(160, 50, 110, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido #001"));

        jButton1.setText("Estado");
        jPanel1.add(jButton1);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 110, 180, 70);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido #004"));

        jButton2.setText("Estado");
        jPanel2.add(jButton2);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(280, 200, 180, 70);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido #008"));

        jButton5.setText("Estado");
        jPanel5.add(jButton5);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(280, 380, 180, 70);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido #002"));

        jButton6.setText("Estado");
        jPanel6.add(jButton6);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(280, 110, 180, 70);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido #001"));

        jButton7.setText("Estado");
        jPanel7.add(jButton7);

        getContentPane().add(jPanel7);
        jPanel7.setBounds(280, 110, 180, 70);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido #003"));

        jButton8.setText("Estado");
        jPanel8.add(jButton8);

        getContentPane().add(jPanel8);
        jPanel8.setBounds(30, 200, 180, 70);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido #005"));

        jButton9.setText("Estado");
        jPanel9.add(jButton9);

        getContentPane().add(jPanel9);
        jPanel9.setBounds(30, 290, 180, 70);

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido #006"));

        jButton10.setText("Estado");
        jPanel10.add(jButton10);

        getContentPane().add(jPanel10);
        jPanel10.setBounds(280, 290, 180, 70);

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido #007"));

        jButton11.setText("Estado");
        jPanel11.add(jButton11);

        getContentPane().add(jPanel11);
        jPanel11.setBounds(30, 380, 180, 70);

        jButton12.setText("Salir");
        getContentPane().add(jButton12);
        jButton12.setBounds(360, 480, 100, 40);

        setSize(new java.awt.Dimension(554, 606));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(S2M12021_Proyecto02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(S2M12021_Proyecto02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(S2M12021_Proyecto02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(S2M12021_Proyecto02.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new S2M12021_Proyecto02().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
